import { Icon } from "leaflet";

let icons: {
  [index: string]: Icon
} = {
  spear: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/arrowhead.svg", iconSize: [32, 32], className: "marker" }),
  dark: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/moon.svg", iconSize: [32, 32], className: "marker" }),
  identifyItem: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/magnifying-glass.svg", iconSize: [32, 32], className: "marker" }),
  dagger: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/stiletto.svg", iconSize: [32, 32], className: "marker" }),
  spirit: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/aura.svg", iconSize: [32, 32], className: "marker" }),
  perception: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/eye-target.svg", iconSize: [32, 32], className: "marker" }),
  meditation: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/meditation.svg", iconSize: [32, 32], className: "marker" }),
  earth: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/stone-pile.svg", iconSize: [32, 32], className: "marker" }),
  repairItem: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/auto-repair.svg", iconSize: [32, 32], className: "marker" }),
  fire: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/flame.svg", iconSize: [32, 32], className: "marker" }),
  bodyBuilding: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/muscle-up.svg", iconSize: [32, 32], className: "marker" }),
  light: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/sun.svg", iconSize: [32, 32], className: "marker" }),
  bank: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/bank.svg", iconSize: [32, 32], className: "marker" }),
  mace: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/flanged-mace.svg", iconSize: [32, 32], className: "marker" }),
  body: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/person.svg", iconSize: [32, 32], className: "marker" }),
  axe: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/battle-axe.svg", iconSize: [32, 32], className: "marker" }),
  temple: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/greek-temple.svg", iconSize: [32, 32], className: "marker" }),
  mind: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/psychic-waves.svg", iconSize: [32, 32], className: "marker" }),
  air: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/tornado.svg", iconSize: [32, 32], className: "marker" }),
  sword: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/broadsword.svg", iconSize: [32, 32], className: "marker" }),
  bow: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/high-shot.svg", iconSize: [32, 32], className: "marker" }),
  diplomacy: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/public-speaker.svg", iconSize: [32, 32], className: "marker" }),
  quest: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/uncertainty.svg", iconSize: [32, 32], className: "marker" }),
  merchant: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/cash.svg", iconSize: [32, 32], className: "marker" }),
  stable: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/horse-head.svg", iconSize: [32, 32], className: "marker" }),
  blaster: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/ray-gun.svg", iconSize: [32, 32], className: "marker" }),
  fountain: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/water-fountain.svg", iconSize: [32, 32], className: "marker" }),
  chain: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/chain-mail.svg", iconSize: [32, 32], className: "marker" }),
  house: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/house.svg", iconSize: [32, 32], className: "marker" }),
  learning: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/read.svg", iconSize: [32, 32], className: "marker" }),
  staff: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/wizard-staff.svg", iconSize: [32, 32], className: "marker" }),
  cult: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/church.svg", iconSize: [32, 32], className: "marker" }),
  shield: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/shield.svg", iconSize: [32, 32], className: "marker" }),
  disarmTrap: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/wolf-trap.svg", iconSize: [32, 32], className: "marker" }),
  water: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/droplets.svg", iconSize: [32, 32], className: "marker" }),
  info: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/info.svg", iconSize: [32, 32], className: "marker" }),
  shop: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/shop.svg", iconSize: [32, 32], className: "marker" }),
  dungeon: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/3d-stairs.svg", iconSize: [32, 32], className: "marker" }),
  leather: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/leather-armor.svg", iconSize: [32, 32], className: "marker" }),
  plate: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/shoulder-armor.svg", iconSize: [32, 32], className: "marker" }),
  obelisk: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/obelisk.svg", iconSize: [32, 32], className: "marker" }),
  inn: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/beer-stein.svg", iconSize: [32, 32], className: "marker" }),
  docks: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/anchor.svg", iconSize: [32, 32], className: "marker" }),
  training: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/crossed-swords.svg", iconSize: [32, 32], className: "marker" }),
  townHall: new Icon({ iconUrl: "/mm-tools/images/leaflet/icons/congress.svg", iconSize: [32, 32], className: "marker" }),
};

export default icons;